// Generated by CoffeeScript 1.7.1

/*
  autor Volosincu Bogdan
 */
var c, cont, ext, ol, volo;

Object.prototype.keys = function(o) {
  var keys, prop, _i, _len;
  for (_i = 0, _len = o.length; _i < _len; _i++) {
    prop = o[_i];
    keys = prop;
  }
  return keys;
};

c = {
  extend: function(source) {
    var dest, prop, _i, _len, _ref;
    dest = {
      ext: void 0,
      sup: void 0
    };
    _ref = Object.keys(source);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      prop = _ref[_i];
      dest[prop] = source[prop];
    }
    return dest;
  },
  print: function(obj) {
    var prop;
    return console.log((function() {
      var _i, _len, _ref, _results;
      _ref = Object.keys(obj);
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        prop = _ref[_i];
        _results.push(prop);
      }
      return _results;
    })());
  }
};

ol = {
  aprop: void 0,
  bprop: void 0,
  cprop: void 0,
  dprop: void 0
};

cont = function() {
  this.activ = void 0;
  this.tip = void 0;
  this.prieteni = void 0;
  this.nume = void 0;
  return this.id = void 0;
};

volo = new cont();

ext = c.extend(volo);

c.print(ext);
