// Generated by CoffeeScript 1.7.1

/*
  autor Volosincu Bogdan
 */
var c, cont, ol, volo;

c = {
  extend: function(source) {
    var dest, prop, _i, _len;
    dest = {
      ext: void 0,
      sup: void 0
    };
    for (_i = 0, _len = source.length; _i < _len; _i++) {
      prop = source[_i];
      dest[prop] = source[prop];
    }
    return dest;
  },
  print: function(obj) {
    var prop, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = obj.length; _i < _len; _i++) {
      prop = obj[_i];
      _results.push(console.log(prop));
    }
    return _results;
  }
};

ol = {
  aprop: void 0,
  bprop: void 0,
  cprop: void 0,
  dprop: void 0
};

cont = function() {
  this.activ = void 0;
  this.tip = void 0;
  this.prieteni = void 0;
  this.nume = void 0;
  return this.id = void 0;
};

volo = new cont();

console.log(c.extend(volo));
