// Generated by CoffeeScript 1.7.1

/*
  autor Volosincu Bogdan
 */
var Cup, c, cont, ext, ol, volo,
  __slice = [].slice;

Cup = (function() {
  function Cup() {}

  Cup.prototype.extend = function() {
    var key, object, objects, value, _i, _len;
    objects = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    for (_i = 0, _len = objects.length; _i < _len; _i++) {
      object = objects[_i];
      for (key in object) {
        value = object[key];
        if (object.hasOwnProperty(key)) {
          this[key] = value;
        }
      }
    }
  };

  Cup.prototype.extend_source = function(source, dest) {
    var prop, _i, _len, _ref;
    _ref = Object.keys(source);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      prop = _ref[_i];
      dest[prop] = source[prop];
    }
    return dest;
  };

  Cup.prototype.print = function(obj) {
    var prop;
    return console.log((function() {
      var _i, _len, _ref, _results;
      _ref = Object.keys(obj);
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        prop = _ref[_i];
        _results.push(prop);
      }
      return _results;
    })());
  };

  return Cup;

})();

ol = {
  aprop: void 0,
  bprop: void 0,
  cprop: void 0,
  dprop: void 0
};

cont = function() {
  this.activ = void 0;
  this.tip = void 0;
  this.prieteni = void 0;
  this.nume = void 0;
  return this.id = void 0;
};

volo = new cont();

c = new Cup();

ext = c.extend_source(volo, ol);

c.print(ext);
