// Generated by CoffeeScript 1.7.1
if (Object.prototype.keys != null) {
  Object.prototype.keys = function(o) {
    var keys, prop;
    keys = (function() {
      var _results;
      _results = [];
      for (prop in o) {
        if (o.hasOwnProperty(prop)) {
          _results.push(prop);
        }
      }
      return _results;
    })();
    return keys;
  };
}
