// Generated by CoffeeScript 1.7.1
var handler, ps, subs;

subs = [];

ps = {
  publish: function(nume, data) {
    var key, _i, _len;
    for (_i = 0, _len = subs.length; _i < _len; _i++) {
      key = subs[_i];
      ps.call_(key, nume, data);
    }
    return false;
  },
  subscribe: function(nume_, func_) {
    subs.push({
      nume: nume_,
      func: func_
    });
    return false;
  },
  call_: function(obj, nume_, data_) {
    if (obj.nume === nume_) {
      obj.func.call(null, data_);
      return false;
    }
  }
};

handler = function(value) {
  console.log(value);
  return false;
};

ps.subscribe("add", handler);

ps.publish("add", "just a value");
