// Generated by CoffeeScript 1.7.1

/*
  autor Volosincu Bogdan
 */
var fna, fnb, moda, modb;

moda = {
  nume: 'nedefinit',
  fn: function(param) {
    if (param != null) {
      this.nume = param;
    }
    console.log(this.nume);
    return false;
  },
  setNume: function(nume, fn) {
    this.nume = nume;
    if (fn != null) {
      fn.call(this, nume);
    }
    return false;
  }
};

modb = {
  nume: 'nedefinit',
  fn: function(param) {
    if (param != null) {
      this.nume = param;
    }
    console.log(this.nume);
    return false;
  },
  numeAdaugat: function(nume) {
    console.log("in a so adaugat numele " + nume);
    return false;
  }
};

fna = moda.fn;

fnb = modb.fn;

moda.nume = 'bogdan';

modb.nume = 'mihai';

moda.setNume('bogdan', modb.numeAdaugat);
