// Generated by CoffeeScript 1.7.1

/*
  autor Volosincu Bogdan
 */
define([], function() {
  "use strict";
  var Proto;
  Proto = (function() {
    var callbacks;

    callbacks = {};

    function Proto(object) {
      var fn, key;
      for (key in object) {
        fn = object[key];
        Proto.prototype[key] = function() {
          var i, k, _i, _len, _ref;
          _ref = callbacks[key];
          for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
            k = _ref[i];
            k.apply(null, i === 0 ? arguments : void 0);
          }
        };
        callbacks[key] = [fn];
      }
    }

    Proto.prototype.sub = function(prop, fn) {
      callbacks[prop].push(fn);
    };

    return Proto;

  })();
  return Proto;
});
