// Generated by CoffeeScript 1.7.1

/*
  autor Volosincu Bogdan
 */
define([], function() {
  "use strict";
  var Proto;
  Proto = (function() {
    var callbacks;

    callbacks = {};

    function Proto(object) {
      var fn, key;
      for (key in object) {
        fn = object[key];
        Proto.prototype[key] = function() {
          var k, _i, _len, _ref;
          _ref = callbacks[key];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            k = _ref[_i];
            k.call(null);
          }
        };
        callbacks[key] = [fn];
      }
      console.log(callbacks);
    }

    Proto.prototype.pub = function() {
      console.log("bum");
    };

    Proto.prototype.sub = function(prop, fn) {
      callbacks[prop].push(fn);
    };

    return Proto;

  })();
  return Proto;
});
