// Generated by CoffeeScript 1.7.1
define([], function() {
  "use strict";
  if (Object.prototype.keys === void 0) {
    Object.prototype.keys = function(o) {
      var keys, prop;
      keys = (function() {
        var _results;
        _results = [];
        for (prop in o) {
          if (o.hasOwnProperty(prop)) {
            _results.push(prop);
          }
        }
        return _results;
      })();
      return keys;
    };
  }
  if ([].indexOf === void 0) {
    Array.prototype.indexOf = function(element, fromIndex) {
      var el, i, index, _i, _len;
      if (fromIndex === void 0) {
        fromIndex = 0;
      }
      index = -1;
      if (this.length > 0) {
        for (el = _i = 0, _len = this.length; _i < _len; el = ++_i) {
          i = this[el];
          console.log(i);
          console.log(el);
          return;
        }
      }
    };
  }
});
