// Generated by CoffeeScript 1.7.1

/*
  autor Volosincu Bogdan
 */
(function(context, factory) {
  if (typeof define === 'function' && define.amd) {
    define(['exports'], function(exports) {
      context.Proto = factory(context, exports);
      return context.Proto;
    });
  } else if (typeof exports !== 'undefined') {
    factory(context, exports);
  } else {
    context.Proto = factory(context, {});
  }
})(this, function(context, Proto) {
  Proto = (function() {
    var cbk_attached, cbk_on, isFunction;

    cbk_on = {};

    cbk_attached = {};

    isFunction = function(o) {
      return typeof o === 'function';
    };

    function Proto(object) {
      var key, value;
      for (key in object) {
        value = object[key];
        if (isFunction(value)) {
          Proto.prototype[key] = function() {
            var i, k, result, _i, _len, _ref;
            result = {};
            _ref = cbk_attached[key];
            for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
              k = _ref[i];
              if (k !== void 0) {
                if (i === 0) {
                  result = k.apply(Proto.prototype, arguments);
                } else {
                  k.apply(Proto.prototype);
                }
              }
            }
            return result;
          };
          cbk_attached[key] = [value];
        } else {
          Proto.prototype[key] = value;
        }
      }
    }

    Proto.prototype.attachTo = function(prop, theFunc, withPriority) {
      if (arguments[3] === void 0) {
        withPriority = cbk_attached[prop].length++;
      }
      if (cbk_attached[prop][withPriority] === void 0 || cbk_attached[prop][withPriority] === null) {
        cbk_attached[prop][withPriority] = theFunc;
      } else {
        Array.prototype.splice.call(cbk_attached[prop], withPriority, 0, theFunc);
      }
    };

    Proto.prototype.on = function(cbk_name, cbk) {
      cbk_on[cbk_name] = cbk;
    };

    Proto.prototype.trigger = function(context, cbk_name, params) {
      var rez;
      rez = {};
      if (arguments.length > 0) {
        rez = cbk_on[cbk_name].apply(context, params);
      } else {
        rez = cbk_on;
      }
      return rez;
    };

    return Proto;

  })();
  return Proto;
});
