// Generated by CoffeeScript 1.7.1

/*
  autor Volosincu Bogdan
 */
define([], function() {
  "use strict";
  (function() {
    var Moda, Modb, fna, fnb, moda, modb;
    Moda = (function() {
      function Moda() {}

      Moda.prototype.nume = 'nedefinit';

      Moda.prototype.fn = function(param) {
        if (param != null) {
          this.nume = param;
        }
        console.log(this.nume);
      };

      Moda.prototype.setNume = function(nume, fn) {
        this.nume = nume;
        if (fn != null) {
          fn.call(this, nume);
        }
      };

      return Moda;

    })();
    Modb = (function() {
      function Modb() {}

      Modb.prototype.nume = 'nedefinit';

      Modb.prototype.fn = function(param) {
        if (param != null) {
          this.nume = param;
        }
        console.log(this.nume);
      };

      Modb.prototype.numeAdaugat = function(nume) {
        console.log("in a so adaugat numele " + nume);
      };

      return Modb;

    })();
    moda = new Moda();
    modb = new Modb();
    fna = moda.fn;
    fnb = modb.fn;
    moda.nume = 'bogdan';
    modb.nume = 'mihai';
    moda.setNume('bogdan', modb.numeAdaugat);
  })();
});
