// Generated by CoffeeScript 1.7.1
define(['jasmine', 'proto'], function(jasmine, Proto) {
  "use strict";
  describe("Test trigger() subscriber list size => ", function() {
    it("On (cnk_on) subscribers list is empty.", function() {
      var o, proto_;
      o = {
        name: 'Bogdan',
        surname: 'Volosincu',
        language: 'JavaScript'
      };
      proto_ = new Proto(o);
      expect(Object.keys(proto_.trigger()).length).toEqual(0);
    });
  });
});
